# 深層学習スクラッチ リカレントニューラルネットワーク

【問題1】SimpleRNNのフォワードプロパゲーション実装

In [16]:
import numpy as np

class acttanh:
    def forward(self, A):
        self.A = A
        return np.tanh(A)
    
    def backward(self, dZ):
        return dZ * (1 - (np.tanh(self.A))**2)
    
class actrelu:
    def forward(self, A):
        self.A = A
        return np.clip(A, 0, None)
    
    def backward(self, dZ):
        return dZ * np.clip(np.sign(self.A), 0, None)

class ScratchSimpleRNNClassifier:
    def __init__(self, n_nodes=10, func_act='tanh'):
        self.n_nodes = n_nodes
        self.W_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]])/100 # (
        self.B = np.array([1, 1, 1, 1]) # (n_nodes,)
        if func_act == 'tanh':
            self.activation = acttanh()
        elif func_act == 'relu':
            self.activation = actrelu()
        
    
    def forward(self, X):
        self.input_data = X
        self.batch_size = self.input_data.shape[0]
        self.n_sequense = self.input_data.shape[1]
        self.h = np.zeros((self.batch_size, self.n_nodes))
#         self.get_mini_batch = GetMiniBatch(X, y, batch_size=self.batch_size)
        self.W_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]])/100 # (n_features, n_nodes)
        
        for b in range(self.batch_size):
            for sequense in range(self.n_sequense):
                a_t = np.dot(self.input_data[b, sequense, :], self.W_x) + np.dot(self.h, self.W_h) + self.B
                h_t = self.activation.forward(a_t)
                
                self.h = h_t.reshape(self.batch_size, -1)
                
        self.final_h = self.h
                
        return self.final_h

問題2】小さな配列でのフォワードプロパゲーションの実験

In [14]:
x = np.array([[[1, 2], [2, 3], [3, 4]]])/100 # (batch_size, n_sequences, n_features)

In [20]:
ssrnn = ScratchSimpleRNNClassifier(n_nodes=4)
res = ssrnn.forward(x)
res

array([[0.79494228, 0.81839002, 0.83939649, 0.85584174]])

正解出力：np.array([[0.79494228, 0.81839002, 0.83939649, 0.85584174]]) # (batch_size, n_nodes)